### ISSUE TITLE
v0.1 TODO list

### ISSUE THREAD

**Issue by kerryChen95** [kerryChen95/react-prevent-outside-scroll#1]
* [ ] setup auto test
  * [ ] test prevent scroll
  * [ ] test `<PreventOutsideScroll>`'s user set `ref` on children
* [ ] support prevent horizontal scroll
* [ ] be compatible with more wheel events
